site_name: Life1 expansion use-case
nav:
    - Home: index.md
    - Requirements analysis: requirements.md
    - Scope: scope.md
    - Current System Architecture: current_system.md
    - Target System Architecture: target_system.md
    - About: about.md
theme:
    name: material
    custom_dir: docs/overrides